# Generated by Django 5.0.3 on 2024-04-04 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'Компания'), (2, 'Соискатель')], default=2, verbose_name='Тип пользователя')),
                ('username', models.CharField(max_length=255, verbose_name='Ф.И.О')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=13, unique=True, verbose_name='Номер телефона')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Обычный пользователь'), (2, 'Модератор')], default=1)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
                ('is_stuff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Все пользователи',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('industry', models.CharField(blank=True, choices=[('Веб-разработка', 'Веб-разработка'), ('Мобильная разработка', 'Мобильная разработка'), ('Базы данных', 'Базы данных'), ('Кибербезопасность', 'Кибербезопасность'), ('Искусственный интеллект и машинное обучение', 'Искусственный интеллект и машинное обучение'), ('Сетевые технологии', 'Сетевые технологии'), ('IT-консалтинг', 'IT-консалтинг')], default=None, max_length=250, null=True, verbose_name='Название отрасли')),
                ('other_industry', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название отрасли(другое)')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('speciality', models.CharField(blank=True, choices=[('Python-разработчик', 'Python-разработчик'), ('JavaScript-разработчик', 'JavaScript-разработчик'), ('Android-разработчик', 'Android-разработчик'), ('iOS-разработчик', 'iOS-разработчик'), ('Специалист по базам данных (DBA)', 'Специалист по базам данных (DBA)'), ('Исследователь данных', 'Исследователь данных'), ('Специалист по безопасности информации (InfoSec)', 'Специалист по безопасности информации (InfoSec)'), ('IT-консультант', 'IT-консультант'), ('Системный администратор', 'Системный администратор')], default=None, max_length=255, null=True, verbose_name='Укажите свою специальность ')),
                ('other_speciality', models.CharField(blank=True, choices=[('Python-разработчик', 'Python-разработчик'), ('JavaScript-разработчик', 'JavaScript-разработчик'), ('Android-разработчик', 'Android-разработчик'), ('iOS-разработчик', 'iOS-разработчик'), ('Специалист по базам данных (DBA)', 'Специалист по базам данных (DBA)'), ('Исследователь данных', 'Исследователь данных'), ('Специалист по безопасности информации (InfoSec)', 'Специалист по безопасности информации (InfoSec)'), ('IT-консультант', 'IT-консультант'), ('Системный администратор', 'Системный администратор')], default=None, max_length=255, null=True, verbose_name='Укажите свою специальность(другое) ')),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатели',
            },
            bases=('users.user',),
        ),
    ]
