# Generated by Django 5.0.3 on 2024-04-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/cover', verbose_name='Ваше фото'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='uniqueId',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Уникальный id'),
        ),
    ]
