# Generated by Django 5.0.3 on 2024-04-03 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Бэкенд - разработка', 'Бэкенд - разработка'), ('Фронтенд-разработка', 'Фронтенд-разработка'), ('Дизайн', 'Дизайн'), ('Тестирование и QA ', 'Тестирование и QA '), ('Администрирование и DevOps', 'Администрирование и DevOps'), ('Управление проектами', 'Управление проектами'), ('Аналитика и анализ данных', 'Аналитика и анализ данных')], default=None, max_length=250, null=True, verbose_name='Название категории')),
                ('other_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название категории(другое)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Стажер (Intern)', 'Стажер (Intern)'), ('Джуниор (Junior)', 'Джуниор (Junior)'), ('Мидл (Middle)', 'Мидл (Middle)'), ('Синьор (Senior)', 'Синьор (Senior)'), ('Ведущий (Lead)', 'Ведущий (Lead)'), ('Эксперт (Expert)', 'Эксперт (Expert)')], default=None, max_length=250, null=True, verbose_name='Уровень опыта')),
                ('other_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Уровень опыта(другое)')),
            ],
            options={
                'verbose_name': 'Уровень опыта',
                'verbose_name_plural': 'Уровени опыта',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Веб-разработка', 'Веб-разработка'), ('Мобильная разработка', 'Мобильная разработка'), ('Базы данных', 'Базы данных'), ('Кибербезопасность', 'Кибербезопасность'), ('Искусственный интеллект и машинное обучение', 'Искусственный интеллект и машинное обучение'), ('Сетевые технологии', 'Сетевые технологии'), ('IT-консалтинг', 'IT-консалтинг')], default=None, max_length=250, null=True, verbose_name='Название отрасли')),
                ('other_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название отрасли(другое)')),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Python-разработчик', 'Python-разработчик'), ('JavaScript-разработчик', 'JavaScript-разработчик'), ('Android-разработчик', 'Android-разработчик'), ('iOS-разработчик', 'iOS-разработчик'), ('Специалист по базам данных (DBA)', 'Специалист по базам данных (DBA)'), ('Исследователь данных', 'Исследователь данных'), ('Специалист по безопасности информации (InfoSec)', 'Специалист по безопасности информации (InfoSec)'), ('IT-консультант', 'IT-консультант'), ('Системный администратор', 'Системный администратор')], default=None, max_length=250, null=True, verbose_name='Название специализации')),
                ('other_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название специализации(другое)')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250, verbose_name='Название компании')),
                ('location', models.CharField(max_length=500, verbose_name='Место нахождение компании')),
                ('industry', models.ManyToManyField(to='jobs.industry', verbose_name='Сфера деятельности')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Зарплата')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Актуально'), (2, 'Не актуально')], default=2)),
                ('contacts', models.CharField(max_length=13, unique=True, verbose_name='Контакты')),
                ('category', models.ManyToManyField(to='jobs.category', verbose_name='Категория')),
                ('company', models.ManyToManyField(to='jobs.employer', verbose_name='компания')),
                ('experience', models.ManyToManyField(to='jobs.experience', verbose_name='Уровень опыта')),
                ('industry', models.ManyToManyField(to='jobs.industry', verbose_name='Отрасль')),
                ('specializing', models.ManyToManyField(to='jobs.speciality', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='Сопроводительное письмо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(upload_to='media/resume', verbose_name='Добавьте свое резюме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.vacancy', verbose_name='Выберите вакансию')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
        migrations.CreateModel(
            name='Chosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.vacancy', verbose_name='Выберите вакансию')),
            ],
            options={
                'verbose_name': 'Избранный',
                'verbose_name_plural': 'Избранные',
            },
        ),
    ]
