# Generated by Django 5.0.3 on 2024-04-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_vacancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Актуально'), (2, 'Не актуально')], default=2),
        ),
    ]
